import { ASSETS } from "@/app/generated/assets";
import { HeroItem } from "@/data/model/hero.model";
import { tournamentInteractor } from "../../tournament/interactor/tournament.interactor";
import { homeRepository } from "../repository/home.repository";

export const homeInteractor = {
  async getManualHeroes() {
    const heroes = await homeRepository.getManualHeroes();
    // Có thể thêm logic xử lý ở đây, ví dụ:
    // return heroes.filter(h => h.id !== 0);
    return heroes;
  },

  async getFullHeroList() {
    // 1. Lấy Banner thủ công
    const manualHeroes = (await homeRepository.getManualHeroes()).sort(
      (a, b) =>
        new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime()
    );

    // 2. Lấy Banner từ Giải đấu (isVisibleOnHome = true)
    const tournaments = await tournamentInteractor.getTournamentList();
    const activeTournaments = tournaments.filter(t => t.isVisibleOnHome);

    const autoHeroes: HeroItem[] = activeTournaments.map(t => ({
      id: -t.id, // ID âm để tránh trùng ID database
      originalId: t.id,
      imageUrl: t.banner || ASSETS.logo.vfd_logo,
      title: t.name,
      subTitle: t.description || "",
      buttonText: "Đăng ký ngay",
      buttonHref: "/register",
      buttonText2: "Xem chi tiết",
      buttonHref2: `/schedule/${t.id}`,
      isAutoGenerated: true,
    }));

    // Banner giải đấu thường ưu tiên hiện đầu tiên
    return [...manualHeroes, ...autoHeroes];
  },

  // Các hàm CRUD chỉ tác động lên Manual Banner
  async createHero(data: Partial<HeroItem>) {
    return await homeRepository.createHero(data);
  },
  async updateHero(id: number, data: Partial<HeroItem>) {
    return await homeRepository.updateHero(id, data);
  },
  async deleteHero(id: number) {
    return await homeRepository.deleteHero(id);
  }
};
