import { Expose } from "class-transformer";

export class HeroItem {
  @Expose({ name: "id" })
  id!: number;
  @Expose({ name: "imageUrl" })
  imageUrl!: string;
  @Expose({ name: "title" })
  title?: string | null;
  @Expose({ name: "subTitle" })
  subTitle?: string | null;
  @Expose({ name: "buttonText" })
  buttonText?: string | null;
  @Expose({ name: "buttonHref" })
  buttonHref?: string | null;
  @Expose({ name: "buttonText2" })
  buttonText2?: string | null;
  @Expose({ name: "buttonHref2" })
  buttonHref2?: string | null;
  @Expose({ name: "createdAt" })
  createdAt?: Date;
  @Expose({ name: "updatedAt" })
  updatedAt?: Date;

  isAutoGenerated?: boolean;
  originalId?: number;
}
